apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-fastapi-app
  namespace: sre-lab
  labels:
    app: sre-fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-fastapi-app
  template:
    metadata:
      labels:
        app: sre-fastapi-app
    spec:
      containers:
        - name: sre-fastapi-app
          image: sre-fastapi-app:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "kubernetes"
            - name: APP_VERSION
              value: "0.1.0"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
