apiVersion: v1
kind: Service
metadata:
  name: sre-fastapi-service
  namespace: sre-lab
  labels:
    app: sre-fastapi-app
spec:
  type: ClusterIP
  selector:
    app: sre-fastapi-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
